export { Main } from "./Main";
export { Story } from "./Story";
export { Roadmap } from "./Roadmap";
export { Utility } from "./Utility";
export { Gallery } from "./Gallery";
export { Team } from "./Team";
export { Partners } from "./Partners";
export { Faq } from "./Faq";
export { Footer } from "./Footer";
